import numpy as np
import numpy.typing as npt
from typing import Any

class HyperDual:
    f: float
    f1: float
    f2: float
    f12: float

    def __init__(self, f: float, f1: float = 0.0, f2: float = 0.0, f12: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...

    # Arithmetic
    def __add__(self, other: "HyperDual | float | int") -> "HyperDual": ...
    def __radd__(self, other: "float | int") -> "HyperDual": ...
    def __sub__(self, other: "HyperDual | float | int") -> "HyperDual": ...
    def __rsub__(self, other: "float | int") -> "HyperDual": ...
    def __mul__(self, other: "HyperDual | float | int") -> "HyperDual": ...
    def __rmul__(self, other: "float | int") -> "HyperDual": ...
    def __truediv__(self, other: "HyperDual | float | int") -> "HyperDual": ...
    def __rtruediv__(self, other: "float | int") -> "HyperDual": ...
    def __pow__(self, other: "HyperDual | float | int") -> "HyperDual": ...
    def __rpow__(self, other: "float | int") -> "HyperDual": ...
    def __neg__(self) -> "HyperDual": ...
    def __pos__(self) -> "HyperDual": ...
    def __abs__(self) -> "HyperDual": ...

    # Comparisons
    def __lt__(self, other: "HyperDual | float | int") -> bool: ...
    def __le__(self, other: "HyperDual | float | int") -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: "HyperDual | float | int") -> bool: ...
    def __ge__(self, other: "HyperDual | float | int") -> bool: ...

    # Transcendentals
    def sin(self) -> "HyperDual": ...
    def cos(self) -> "HyperDual": ...
    def tan(self) -> "HyperDual": ...
    def exp(self) -> "HyperDual": ...
    def log(self) -> "HyperDual": ...
    def sqrt(self) -> "HyperDual": ...
    def square(self) -> "HyperDual": ...
    def arcsin(self) -> "HyperDual": ...
    def arccos(self) -> "HyperDual": ...
    def arctan(self) -> "HyperDual": ...
    def sinh(self) -> "HyperDual": ...
    def cosh(self) -> "HyperDual": ...
    def tanh(self) -> "HyperDual": ...
    def arcsinh(self) -> "HyperDual": ...
    def arccosh(self) -> "HyperDual": ...
    def arctanh(self) -> "HyperDual": ...
    def log2(self) -> "HyperDual": ...
    def log10(self) -> "HyperDual": ...
    def exp2(self) -> "HyperDual": ...
    def log1p(self) -> "HyperDual": ...
    def expm1(self) -> "HyperDual": ...
    def cbrt(self) -> "HyperDual": ...
    def sign(self) -> "HyperDual": ...
    def conjugate(self) -> "HyperDual": ...
    def floor(self) -> "HyperDual": ...
    def ceil(self) -> "HyperDual": ...

def hessian_matrix(fun: Any, x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
