name: Benchmark

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e ".[test,benchmark]"

      - name: Run benchmarks
        run: pytest tests/test_benchmark.py --benchmark-json=output.json --benchmark-only

      - name: Store benchmark result
        if: github.ref == 'refs/heads/master'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "pytest"
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "130%"
          comment-on-alert: true
          fail-on-alert: false
